### ISSUE TITLE
Building fails due to canairio_sensorlib

### ISSUE THREAD

**Issue by dcflachs** [hpsaturn/co2_m5coreink#7]
It appears that the package hpsaturn/CanAirIO Air Quality Sensors Library is no longer available at version 0.5.4, nor are some of its dependencies. Newer versions of the library dont seem to work correctly with the Core Ink, in particular they only detect sensors on the initial loop and then fail to find anything on subsequent loops.

**Comment by hpsaturn** [comment]
Thanks to notify it. Yes is true. The new version of the M5 libraries and also the new versions of CanAirIO have problems with this device. For this reason some months ago I fixed to this specific number. But, for your report, I notice that some old dependencies of this version has problem too.

I changed the target to: https://github.com/kike-canaries/canairio_sensorlib.git#v0.5.4 because PlatformIO registry sounds that not saves old versions :( and for that:

We have the next dependencies broken:
```
Library Manager: Installing adafruit/Adafruit BMP280 Library @ 2.6.1
Library Manager: Warning! Could not install `{'name': 'Adafruit BMP280 Library', 'owner': 'adafruit', 'version': '2.6.1'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing adafruit/Adafruit BME680 Library @ 2.0.1
Library Manager: Warning! Could not install `{'name': 'Adafruit BME680 Library', 'owner': 'adafruit', 'version': '2.0.1'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing adafruit/Adafruit BusIO @ 1.11.1
Library Manager: Warning! Could not install `{'name': 'Adafruit BusIO', 'owner': 'adafruit', 'version': '1.11.1'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing adafruit/Adafruit SHT31 Library @ 2.0.0
Library Manager: Warning! Could not install `{'name': 'Adafruit SHT31 Library', 'owner': 'adafruit', 'version': '2.0.0'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing robtillaart/AM232X @ 0.4.1
Library Manager: Warning! Could not install `{'name': 'AM232X', 'owner': 'robtillaart', 'version': '0.4.1'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing paulvha/sps30 @ 1.4.12
Library Manager: Warning! Could not install `{'name': 'sps30', 'owner': 'paulvha', 'version': '1.4.12'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing wifwaf/MH-Z19 @ 1.5.3
Library Manager: Warning! Could not install `{'name': 'MH-Z19', 'owner': 'wifwaf', 'version': '1.5.3'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing sparkfun/SparkFun SCD30 Arduino Library @ 1.0.17
Library Manager: Warning! Could not install `{'name': 'SparkFun SCD30 Arduino Library', 'owner': 'sparkfun', 'version': '1.0.17'}` dependency for the`CanAirIO Air Quality Sensors Library` package
Library Manager: Installing sensirion/Sensirion Core @ 0.5.3
Library Manager: Warning! Could not install `{'name': 'Sensirion Core', 'owner': 'sensirion', 'version': '0.5.3'}` dependency for the`CanAirIO Air Quality Sensors Library` package
```
A temporal fix, could be put these versions on the platformio.ini and this SensorsLibrary tag target. Of course better we could try to understand why the last versions of these third party libraries doesn't works with this device setup.

**Comment by hpsaturn** [comment]
please let me know if this temporal pull request #8, fix the issue.

**Comment by dcflachs** [comment]
@hpsaturn Yes #8 restores the functionality of the project. Thank you! 
When i have more time to play around with this i may take a crack at figuring out why the newer libraries fail.
